ZOHO_PRODUCTS_DICT = {
    'GSUITE_BASIC': '',
    'GSUITE_BUSINESS': '',
    'GSUITE_STANDARD': '',
    'GSUITE_ENTERPRISE': '',
    'GSUITE_LITE': '',
    'GSUITE_EDUCATION': '',
    'GAMS': '',
    'GDR_20GB': '',
    'GDR_50GB': '',
    'GDR_200GB': '',
    'GDR_400GB': '',
    'GDR_1TB': '',
    'GDR_2TB': '',
    'GDR_4TB': '',
    'GDR_8TB': '',
    'GDR_16TB': '',
    'GV': '',
    'GV_FE': '',
    'CDM': '',
}
