image: hoozecn/sm
services:
  - postgres
  - redis

variables:
  DJANGO_SETTINGS_MODULE: 'app.ci_settings'

stages:
  - test

job_main:
  script:
    - env
    - pip install -r requirements.txt
    - python manage.py test --with-coverage
    - coverage html
    - grep pc_cov htmlcov/index.html | egrep -o "[0-9]+\%" | awk '{ print "covered " $1;}'
  stage: test