# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSCTestDomain',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255, null=True, verbose_name=b'Domain', blank=True)),
                ('license_number', models.CharField(max_length=255, null=True, verbose_name=b'License Number', blank=True)),
                ('plan', models.CharField(max_length=255, null=True, verbose_name=b'Plan', blank=True)),
                ('status', models.CharField(max_length=255, null=True, verbose_name=b'Status', blank=True)),
                ('primary', models.BooleanField(default=False, verbose_name=b'Is Primary')),
                ('org_name', models.CharField(max_length=255, null=True, verbose_name=b'Organization Name', blank=True)),
                ('lang', models.CharField(max_length=31, null=True, verbose_name=b'Language Code', blank=True)),
                ('country', models.CharField(max_length=255, null=True, verbose_name=b'Country Code', blank=True)),
                ('secondary_email', models.CharField(max_length=255, null=True, verbose_name=b'Secondary Email', blank=True)),
                ('users', models.IntegerField(default=0, null=True, verbose_name=b'Users Number', blank=True)),
                ('apps_creation', models.DateTimeField(null=True, verbose_name=b'Apps Creation', blank=True)),
                ('apps_expiry', models.DateTimeField(null=True, verbose_name=b'Apps Expiry', blank=True)),
                ('apps_version', models.CharField(max_length=31, null=True, blank=True)),
                ('max_licenses', models.IntegerField(default=0, null=True, verbose_name=b'Max licenses', blank=True)),
                ('reseller', models.CharField(max_length=1023, null=True, blank=True)),
            ],
            options={
                'db_table': 'gsc_test_domain',
            },
        ),
        migrations.CreateModel(
            name='GSCTestUser',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, null=True, verbose_name=b'Email', blank=True)),
                ('granted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gsc_test_user',
            },
        ),
        migrations.CreateModel(
            name='MockZohoAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(serialize=False, verbose_name=b'Id', primary_key=True)),
                ('domain', models.CharField(max_length=255, null=True, verbose_name=b'Domain', blank=True)),
                ('gsc_installed', models.CharField(max_length=31, null=True, verbose_name=b'GSC Installed?', blank=True)),
                ('phone', models.CharField(max_length=255, null=True, verbose_name=b'Phone', blank=True)),
                ('gsc_install_status', models.CharField(max_length=255, null=True, verbose_name=b'GSC Install Status', blank=True)),
                ('lead_source', models.CharField(max_length=255, null=True, verbose_name=b'Lead Source', blank=True)),
                ('total_revenue', models.CharField(max_length=255, null=True, verbose_name=b'Total Revenue', blank=True)),
                ('payment_position', models.CharField(max_length=255, null=True, verbose_name=b'Payment Position', blank=True)),
                ('first_payment_date', models.CharField(max_length=255, null=True, verbose_name=b'First Payment Date', blank=True)),
                ('first_payment_id', models.CharField(max_length=255, null=True, verbose_name=b'First Payment ID', blank=True)),
                ('last_payment_date', models.CharField(max_length=255, null=True, verbose_name=b'Last Payment Date', blank=True)),
                ('last_payment_id', models.CharField(max_length=255, null=True, verbose_name=b'Last Payment ID', blank=True)),
                ('last_payment_outcome', models.CharField(max_length=255, null=True, verbose_name=b'Last Payment Outcome', blank=True)),
                ('last_payment_type', models.CharField(max_length=255, null=True, verbose_name=b'Last Payment Type', blank=True)),
                ('account_type', models.CharField(max_length=255, null=True, verbose_name=b'Account Type', blank=True)),
                ('gsc_reseller_id', models.CharField(max_length=255, null=True, verbose_name=b'GSC Reseller_ID', blank=True)),
                ('account_name', models.CharField(max_length=255, null=True, verbose_name=b'Account Name', blank=True)),
                ('gapps_version', models.CharField(max_length=255, null=True, verbose_name=b'GAPPS Version', blank=True)),
                ('language_code', models.CharField(max_length=255, null=True, verbose_name=b'Language Code', blank=True)),
                ('google_org_name', models.CharField(max_length=255, null=True, verbose_name=b'Google Organization Name', blank=True)),
                ('max_licenses', models.CharField(max_length=255, null=True, verbose_name=b'Max licenses', blank=True)),
                ('email', models.CharField(max_length=255, null=True, verbose_name=b'Email', blank=True)),
                ('name', models.CharField(max_length=255, null=True, verbose_name=b'Name', blank=True)),
                ('admin_email', models.CharField(max_length=255, null=True, verbose_name=b'Admin Email', blank=True)),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name=b'First Name', blank=True)),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name=b'Last Name', blank=True)),
                ('communication_first_name', models.CharField(max_length=255, null=True, verbose_name=b'Communication First Name', blank=True)),
                ('communication_last_name', models.CharField(max_length=255, null=True, verbose_name=b'Communication Last Name', blank=True)),
                ('contact_id', models.CharField(max_length=255, null=True, verbose_name=b'Contact ID', blank=True)),
                ('gsc', models.CharField(max_length=255, null=True, verbose_name=b'GSC', blank=True)),
                ('account_id', models.CharField(max_length=255, null=True, verbose_name=b'Account ID', blank=True)),
                ('secondary_email', models.CharField(max_length=255, null=True, verbose_name=b'Secondary Name', blank=True)),
                ('number_of_accounts', models.CharField(max_length=255, null=True, verbose_name=b'Number of Accounts', blank=True)),
                ('number_of_licences', models.CharField(max_length=255, null=True, verbose_name=b'Number of Licences', blank=True)),
                ('gsc_install', models.CharField(max_length=255, null=True, verbose_name=b'GSC Install', blank=True)),
                ('gsc_expiry', models.CharField(max_length=255, null=True, verbose_name=b'GSC Expiry', blank=True)),
                ('gsc_status', models.CharField(max_length=255, null=True, verbose_name=b'GSC Status', blank=True)),
                ('gsc_commitment', models.CharField(max_length=255, null=True, verbose_name=b'GSC Commitment', blank=True)),
                ('gsc_renewal_option', models.CharField(max_length=255, null=True, verbose_name=b'GSC Renewal Option', blank=True)),
                ('gsc_version', models.CharField(max_length=255, null=True, verbose_name=b'GSC Version', blank=True)),
                ('cancelled_by_user', models.CharField(max_length=255, null=True, verbose_name=b'Cancelled by User', blank=True)),
                ('billing_code', models.CharField(max_length=255, null=True, verbose_name=b'Billing Code', blank=True)),
                ('billing_street', models.CharField(max_length=255, null=True, verbose_name=b'Billing Street', blank=True)),
                ('billing_city', models.CharField(max_length=255, null=True, verbose_name=b'Billing City', blank=True)),
                ('billing_state', models.CharField(max_length=255, null=True, verbose_name=b'Billing State', blank=True)),
                ('braintree_id', models.CharField(max_length=255, null=True, verbose_name=b'Braintree ID', blank=True)),
                ('paypal_failure', models.CharField(max_length=255, null=True, verbose_name=b'Paypal Failure', blank=True)),
                ('paypal_gateway', models.CharField(max_length=255, null=True, verbose_name=b'Paypal Gateway', blank=True)),
                ('trusted', models.CharField(max_length=255, null=True, verbose_name=b'Trusted', blank=True)),
                ('main_contact_email', models.CharField(max_length=255, null=True, verbose_name=b'Main Contact Email', blank=True)),
                ('reseller_email', models.CharField(max_length=255, null=True, verbose_name=b'Reseller Email', blank=True)),
                ('google_reseller_name', models.CharField(max_length=255, null=True, verbose_name=b'Google Reseller Name', blank=True)),
                ('gsc_stage', models.CharField(max_length=255, null=True, verbose_name=b'GSC stage', blank=True)),
            ],
            options={
                'db_table': 'zoho_test_account',
            },
        ),
        migrations.CreateModel(
            name='MockZohoContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(serialize=False, verbose_name=b'Id', primary_key=True)),
                ('domain', models.CharField(max_length=255, null=True, verbose_name=b'Domain', blank=True)),
                ('google_org_name', models.CharField(max_length=255, null=True, verbose_name=b'Google Organization Name', blank=True)),
                ('phone', models.CharField(max_length=255, null=True, verbose_name=b'Phone', blank=True)),
                ('email', models.CharField(max_length=255, null=True, verbose_name=b'Email', blank=True)),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name=b'First Name', blank=True)),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name=b'Last Name', blank=True)),
                ('mailing_zip', models.CharField(max_length=255, null=True, verbose_name=b'Mailing Zip', blank=True)),
                ('apps_secondary_email', models.CharField(max_length=255, null=True, verbose_name=b'Apps Secondary Email', blank=True)),
                ('language_code', models.CharField(max_length=31, null=True, verbose_name=b'Language Code', blank=True)),
                ('number_of_accounts', models.CharField(max_length=255, null=True, verbose_name=b'Number of Accounts', blank=True)),
                ('secondary_email', models.CharField(max_length=255, null=True, verbose_name=b'Secondary Email', blank=True)),
            ],
            options={
                'db_table': 'zoho_test_contact',
            },
        ),
        migrations.CreateModel(
            name='MockZohoLead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(serialize=False, verbose_name=b'Id', primary_key=True)),
                ('domain', models.CharField(max_length=255, null=True, verbose_name=b'Domain', blank=True)),
                ('email', models.CharField(max_length=255, null=True, verbose_name=b'Email', blank=True)),
                ('admin_email', models.CharField(max_length=255, null=True, verbose_name=b'Admin Email', blank=True)),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name=b'First Name', blank=True)),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name=b'Last Name', blank=True)),
                ('communication_first_name', models.CharField(max_length=255, null=True, verbose_name=b'Communication First Name', blank=True)),
                ('communication_last_name', models.CharField(max_length=255, null=True, verbose_name=b'Communication Last Name', blank=True)),
                ('contact_id', models.CharField(max_length=255, null=True, verbose_name=b'Contact ID', blank=True)),
                ('gsc', models.CharField(max_length=255, null=True, verbose_name=b'GSC', blank=True)),
                ('account_id', models.CharField(max_length=255, null=True, verbose_name=b'Account ID', blank=True)),
                ('account_type', models.CharField(max_length=255, null=True, verbose_name=b'Account Type', blank=True)),
                ('secondary_email', models.CharField(max_length=255, null=True, verbose_name=b'Secondary Email', blank=True)),
                ('phone', models.CharField(max_length=255, null=True, verbose_name=b'Phone', blank=True)),
                ('gsc_install_status', models.CharField(max_length=255, null=True, verbose_name=b'GSC Install Status', blank=True)),
                ('lead_source', models.CharField(max_length=255, null=True, verbose_name=b'Lead Source', blank=True)),
                ('gsc_reseller_id', models.CharField(max_length=255, null=True, verbose_name=b'GSC Reseller_ID', blank=True)),
                ('google_org_name', models.CharField(max_length=255, null=True, verbose_name=b'Google Organization Name', blank=True)),
                ('company_name', models.CharField(max_length=255, null=True, verbose_name=b'Company Name', blank=True)),
                ('language_code', models.CharField(max_length=31, null=True, verbose_name=b'Language Code', blank=True)),
                ('apps_secondary_email', models.CharField(max_length=255, null=True, verbose_name=b'Apps Secondary Email', blank=True)),
                ('country_code', models.CharField(max_length=255, null=True, verbose_name=b'Country Code', blank=True)),
                ('apps_creation', models.CharField(max_length=255, null=True, verbose_name=b'Apps Creation', blank=True)),
                ('apps_expiry', models.CharField(max_length=255, null=True, verbose_name=b'Apps Expiry', blank=True)),
                ('max_licenses', models.CharField(max_length=255, null=True, verbose_name=b'Max licenses', blank=True)),
                ('number_of_accounts', models.CharField(max_length=255, null=True, verbose_name=b'Number of Accounts', blank=True)),
                ('gapps_version', models.CharField(max_length=31, null=True, verbose_name=b'GAPPS Version', blank=True)),
                ('offline_account', models.CharField(max_length=31, null=True, verbose_name=b'Offline Account', blank=True)),
                ('subscription_id', models.CharField(max_length=255, null=True, verbose_name=b'Subscription ID', blank=True)),
                ('subscription_name', models.CharField(max_length=511, verbose_name=b'Subscription Name')),
                ('currency', models.CharField(max_length=31, null=True, verbose_name=b'Currency', blank=True)),
                ('gsc_install', models.CharField(max_length=255, null=True, verbose_name=b'GSC Install', blank=True)),
                ('gsc_expiry', models.CharField(max_length=255, null=True, verbose_name=b'GSC Expiry', blank=True)),
                ('gsc_installed', models.CharField(max_length=31, null=True, verbose_name=b'GSC Installed?', blank=True)),
                ('number_of_licences', models.CharField(max_length=255, null=True, verbose_name=b'Number of Licences', blank=True)),
                ('vendor_status', models.CharField(max_length=255, null=True, verbose_name=b'Vendor Status', blank=True)),
                ('gsc_status', models.CharField(max_length=255, null=True, verbose_name=b'GSC Status', blank=True)),
                ('gsc_version', models.CharField(max_length=255, null=True, verbose_name=b'GSC Version', blank=True)),
            ],
            options={
                'db_table': 'zoho_test_lead',
            },
        ),
        migrations.CreateModel(
            name='MockZohoPotential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(serialize=False, verbose_name=b'Id', primary_key=True)),
                ('type', models.CharField(max_length=255, null=True, verbose_name=b'Type', blank=True)),
                ('stage', models.CharField(max_length=255, null=True, verbose_name=b'Stage', blank=True)),
                ('amount', models.CharField(max_length=255, null=True, verbose_name=b'Amount', blank=True)),
                ('payment_position', models.CharField(max_length=255, null=True, verbose_name=b'Payment Position', blank=True)),
                ('first_payment', models.CharField(max_length=255, null=True, verbose_name=b'First Payment', blank=True)),
                ('closing_date', models.CharField(max_length=255, null=True, verbose_name=b'Closing Date', blank=True)),
                ('gsc_version', models.CharField(max_length=255, null=True, verbose_name=b'GSC Version', blank=True)),
                ('gsc_status', models.CharField(max_length=255, null=True, verbose_name=b'GSC Status', blank=True)),
                ('gsc_commitment', models.CharField(max_length=255, null=True, verbose_name=b'GSC Commitment', blank=True)),
                ('number_of_licences', models.CharField(max_length=255, null=True, verbose_name=b'Number of Licences', blank=True)),
                ('account_name', models.CharField(max_length=255, null=True, verbose_name=b'Account Name', blank=True)),
                ('smownerid', models.CharField(max_length=255, null=True, verbose_name=b'SMOWNERID', blank=True)),
                ('potential_name', models.CharField(max_length=255, null=True, verbose_name=b'Potential Name', blank=True)),
                ('upsell', models.CharField(max_length=255, null=True, verbose_name=b'Upsell', blank=True)),
            ],
            options={
                'db_table': 'zoho_test_potential',
            },
        ),
        migrations.CreateModel(
            name='MockZohoSalesOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(serialize=False, verbose_name=b'Id', primary_key=True)),
                ('subject', models.CharField(max_length=255, null=True, verbose_name=b'Subject', blank=True)),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name=b'First Name', blank=True)),
                ('potential_name', models.CharField(max_length=255, null=True, verbose_name=b'Potential Name', blank=True)),
                ('account_name', models.CharField(max_length=255, null=True, verbose_name=b'Account Name', blank=True)),
                ('product', models.CharField(max_length=255, null=True, verbose_name=b'Product', blank=True)),
                ('quantity', models.CharField(max_length=255, null=True, verbose_name=b'Quantity', blank=True)),
                ('unit_price', models.CharField(max_length=255, null=True, verbose_name=b'Unit Price', blank=True)),
                ('email', models.CharField(max_length=255, null=True, verbose_name=b'Email', blank=True)),
                ('total_price', models.CharField(max_length=31, null=True, verbose_name=b'TOTAL Price', blank=True)),
            ],
            options={
                'db_table': 'zoho_test_sales_order',
            },
        ),
    ]
