FROM python:2.7

RUN apt-get update && apt-get install -y netcat gettext

RUN mkdir /code
RUN pip install --no-cache-dir pip -U
ADD requirements.txt /code
RUN pip install --no-cache-dir -r /code/requirements.txt

WORKDIR /app

ADD /scripts/entrypoint.sh /bin/entrypoint.sh

RUN chmod +x /bin/entrypoint.sh
